const sidebar = {
  dashboardSidebar: [
    "index",
    {
      type: "category",
      label: "Get started",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "get-started" }],
    },
    {
      type: "category",
      label: "How to",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "how-to" }],
    },
  ],
};

module.exports = sidebar;
