/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 The sidebars can be generated from the filesystem, or explicitly defined here.
 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebar = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // snapsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  sdkJavaScriptSidebar: [
    "javascript/index",
    {
      type: "category",
      label: "Get started",
      link: { type: "generated-index", slug: "javascript/get-started" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "javascript/get-started" }],
    },
    {
      type: "category",
      label: "How to",
      link: { type: "generated-index", slug: "javascript/how-to" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "javascript/how-to" }],
    },
    {
      type: "category",
      label: "Concepts",
      link: { type: "generated-index", slug: "javascript/concepts" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "javascript/concepts" }],
    },
    {
      type: "category",
      label: "Tutorials",
      link: { type: "generated-index", slug: "javascript/tutorials" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "javascript/tutorials" }],
    },
    {
      type: "category",
      label: "Reference",
      link: { type: "generated-index", slug: "javascript/reference" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "javascript/reference" }],
    },
  ],

  sdkIosSidebar: [
    "ios/index",
    {
      type: "category",
      label: "Get started",
      link: { type: "generated-index", slug: "ios/get-started" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "ios/get-started" }],
    },
    {
      type: "category",
      label: "How to",
      link: { type: "generated-index", slug: "ios/how-to" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "ios/how-to" }],
    },
    {
      type: "category",
      label: "Concepts",
      link: { type: "generated-index", slug: "ios/concepts" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "ios/concepts" }],
    },
    {
      type: "category",
      label: "Tutorials",
      link: { type: "generated-index", slug: "ios/tutorials" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "ios/tutorials" }],
    },
    {
      type: "category",
      label: "Reference",
      link: { type: "generated-index", slug: "ios/reference" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "ios/reference" }],
    },
  ],

  sdkAndroidSidebar: [
    "android/index",
    {
      type: "category",
      label: "Get started",
      link: { type: "generated-index", slug: "android/get-started" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "android/get-started" }],
    },
    {
      type: "category",
      label: "How to",
      link: { type: "generated-index", slug: "android/how-to" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "android/how-to" }],
    },
    {
      type: "category",
      label: "Concepts",
      link: { type: "generated-index", slug: "android/concepts" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "android/concepts" }],
    },
    {
      type: "category",
      label: "Tutorials",
      link: { type: "generated-index", slug: "android/tutorials" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "android/tutorials" }],
    },
    {
      type: "category",
      label: "Reference",
      link: { type: "generated-index", slug: "android/reference" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "android/reference" }],
    },
  ],

  sdkUnitySidebar: [
    "unity/index",
    {
      type: "category",
      label: "Get started",
      link: { type: "generated-index", slug: "unity/get-started" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "unity/get-started" }],
    },
    {
      type: "category",
      label: "How to",
      link: { type: "generated-index", slug: "unity/how-to" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "unity/how-to" }],
    },
    {
      type: "category",
      label: "Concepts",
      link: { type: "generated-index", slug: "unity/concepts" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "unity/concepts" }],
    },
    {
      type: "category",
      label: "Tutorials",
      link: { type: "generated-index", slug: "unity/tutorials" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "unity/tutorials" }],
    },
    {
      type: "category",
      label: "Reference",
      link: { type: "generated-index", slug: "unity/reference" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "unity/reference" }],
    },
  ],
};

module.exports = sidebar;
