/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 The sidebars can be generated from the filesystem, or explicitly defined here.
 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebar = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // snapsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  sdkSidebar: [
    "index",
    {
      type: "category",
      label: "Get started",
      link: { type: "generated-index", slug: "/get-started" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "get-started" }],
    },
    {
      type: "category",
      label: "How to",
      link: { type: "generated-index", slug: "/how-to" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "how-to" }],
    },
    {
      type: "category",
      label: "Concepts",
      link: { type: "generated-index", slug: "/concepts" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "concepts" }],
    },
    {
      type: "category",
      label: "Tutorials",
      link: { type: "generated-index", slug: "/tutorials" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "tutorials" }],
    },
    {
      type: "category",
      label: "Reference",
      link: { type: "generated-index", slug: "/reference" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "reference" }],
    },
  ],
};

module.exports = sidebar;
