const sidebar = {
  servicesSidebar: [
    "index",
    {
      type: "category",
      label: "Get started",
      link: { type: "generated-index", slug: "/get-started" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "get-started" }],
    },
    {
      type: "category",
      label: "Network APIs",
      link: { type: "generated-index", slug: "/network-apis" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "network-apis" }],
    },
    {
      type: "category",
      label: "Infura Expansion APIs",
      link: { type: "generated-index", slug: "/infura-expansion-apis" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "infura-expansion-apis" }],
    },
    {
      type: "category",
      label: "Learn",
      link: { type: "generated-index", slug: "/learn" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "learn" }],
    },
    {
      type: "category",
      label: "Tutorials",
      link: { type: "generated-index", slug: "/tutorials" },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "tutorials" }],
    },
  ],
};

module.exports = sidebar;

