// @ts-check
console.log(9999, process.env.NODE_ENV);
const isProd = process.env.NODE_ENV === "production";

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebar = {
  walletSidebar: [
    "index",
    {
      type: "category",
      label: "How to",
      link: { type: "generated-index", slug: "/how-to" },
      items: [{ type: "autogenerated", dirName: "how-to" }],
      collapsed: false,
    },
    {
      type: "category",
      label: "Concepts",
      link: { type: "generated-index", slug: "/concepts" },
      items: [{ type: "autogenerated", dirName: "concepts" }],
    },
    {
      type: "category",
      label: "Tutorials",
      link: { type: "generated-index", slug: "/tutorials" },
      items: [
        {
          type: "doc",
          id: "tutorials/react-dapp-local-state",
        },
        {
          type: "doc",
          id: "tutorials/javascript-dapp-simple",
        },
      ],
    },
    {
      ...(!isProd && {
        type: "category",
        label: "New Reference",
        link: { type: "generated-index", slug: "/new-reference" },
        items: [{ type: "autogenerated", dirName: "new-reference" }],
      }),
    },
    {
      type: "category",
      label: "Reference",
      link: { type: "generated-index", slug: "/reference" },
      items: [{ type: "autogenerated", dirName: "reference" }],
    },
  ],
};

module.exports = sidebar;
