// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebar = {
  walletSidebar: [
    "index",
    {
      type: "category",
      label: "Connect to MetaMask",
      link: {type: "doc", id: "connect/index"},
      items: [
        {
          type: "category",
          label: "MetaMask SDK",
          link: {type: "doc", id: "connect/metamask-sdk/index"},
          items: [{ type: "autogenerated", dirName: "connect/metamask-sdk" }],
        },
        {
          type: "category",
          label: "Third-party libraries",
          items: [{ type: "autogenerated", dirName: "connect/3rd-party-libraries" }],
        },
        {
          type: "doc",
          id: "connect/wallet-api",
        },
      ],
      collapsed: false,
    },
    {
      type: "category",
      label: "How to",
      link: { type: "generated-index", slug: "/how-to" },
      items: [{ type: "autogenerated", dirName: "how-to" }],
    },
    {
      type: "category",
      label: "Concepts",
      link: { type: "generated-index", slug: "/concepts" },
      items: [{ type: "autogenerated", dirName: "concepts" }],
    },
    {
      type: "category",
      label: "Tutorials",
      link: { type: "generated-index", slug: "/tutorials" },
      items: [{ type: "autogenerated", dirName: "tutorials" }],
    },
    {
      type: "category",
      label: "Reference",
      link: { type: "generated-index", slug: "/reference" },
      items: [
        {
          type: "doc",
          id: "reference/sdk-js-options",
        },
        {
          type: "doc",
          id: "reference/sdk-unity-api",
        },
        {
          type: "doc",
          id: "reference/provider-api",
        },
      ],
    },
  ],
};

module.exports = sidebar;
