version: 2.1

workflows:
  test-and-deploy:
    jobs:
      - lint
      - build:
          filters:
            branches:
              only:
                - master
          requires:
            - lint

jobs:
  build:
    docker:
      - image: circleci/node:11
    environment:
      - TARGET_BRANCH: gh-pages
    steps:
      - checkout
      - run:
          name: Deploy site
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            yarn
            yarn build
            git checkout $TARGET_BRANCH
            cp -r docs/dist/* .
            git add -A
            git commit -m "Automated deployment: ${CIRCLE_SHA1} [ci skip]" --allow-empty
            git push -f origin $TARGET_BRANCH
  
  lint:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run:
          name: Lint
          command: |
            yarn
            yarn lint
