version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:11
    environment:
      - TARGET_BRANCH: gh-pages
    steps:
      - checkout
      - deploy:
          name: Deploy site
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            npm install
            npm run build
            git checkout $TARGET_BRANCH
            cp -r docs/dist/* .
            git add -A
            git commit -m "Automated deployment: ${CIRCLE_SHA1} [ci skip]" --allow-empty
            git push -f origin $TARGET_BRANCH
            
