version: 2.1

workflows:
  test-and-deploy:
    jobs:
      - prep-deps
      - lint:
          requires:
            - prep-deps
      - build:
          filters:
            branches:
              only:
                - master
          requires:
            - prep-deps
            - lint

jobs:
  build:
    docker:
      - image: circleci/node:11
    environment:
      - TARGET_BRANCH: gh-pages
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploy site
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            yarn build
            git checkout $TARGET_BRANCH
            cp -r docs/dist/* .
            git add -A
            git commit -m "Automated deployment: ${CIRCLE_SHA1} [ci skip]" --allow-empty
            git push -f origin $TARGET_BRANCH
  
  lint:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: |
            yarn lint

  prep-deps:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            yarn --frozen-lockfile --ignore-scripts
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
