name: "💡 Suggestions"
description: "Suggest a new page, section, or edit for an existing page."
title: "[Suggestion]: "
labels: ["type: documentation"]
body:
  - type: textarea
    attributes:
      label: Summary
      description: |
        A clear and concise summary of what we should add.
      placeholder: |
        Example:
        Add a new page for how to use Metamask.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Details
      description: |
        Please provide an explanation for what you're suggesting.
      placeholder: |
        Example:
        I think it would be helpful to have a page that explains how to use Metamask documentation.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Are you working on this?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true 

