---
name: Check for lint, spelling and link errors

on:
  workflow_call:
    secrets:
      SEGMENT_ANALYTICS_KEY:
        required: true
      LD_CLIENT_ID:
        required: true
      SENTRY_KEY:
        required: true

env:
  SEGMENT_ANALYTICS_KEY: ${{ secrets.SEGMENT_ANALYTICS_KEY }}
  LD_CLIENT_ID: ${{ secrets.LD_CLIENT_ID }}
  SENTRY_KEY: ${{ secrets.SENTRY_KEY }}

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Lint
        uses: ConsenSys/github-actions/docs-lint-all@main

  spelling:
    name: Spelling
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file-extensions: ['.md', '.mdx']
    steps:
      - uses: actions/checkout@v4
      - name: Vale
        uses: Consensys/github-actions/docs-spelling-check@main
        with:
          FILEPATHS: 'snaps,services,wallet,developer-tools,docs'

  linkCheck:
    name: Link Checking
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file-extensions: ['.md', '.mdx']
    steps:
      - uses: actions/checkout@v4
      - name: LinkCheck
        uses: ConsenSys/github-actions/docs-link-check@main
        with:
          FILE_EXTENSION: ${{ matrix.file-extensions }}
