---
name: Trivy
on:
  pull_request:
    branches:
      - main

jobs:
  trivy:
    name: Run trivy scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Trivy
        uses: ConsenSys/github-actions/trivy@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
